spring:    
  h2:
    console:
      path: /console
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: 
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: 'true'
    show-sql: 'true'